### ISSUE TITLE
Outdated? 

### ISSUE THREAD

**Issue by kebre001** [napalm-automation-community/napalm-ce#1]
Im trying to get this to work with a Huawei CE6870 with no success.

The first issue I encountered was a Python error:

> Reason: 'map' object is not reversible!

which is caused by _get_flash_size ([here](https://github.com/napalm-automation-community/napalm-ce/blob/master/napalm_ce/ce.py#L1130)) where you try to iterate a map.

This I solved by adding:
`num_list = list(num_list) `
directly after the declaration of num_list

When that was solved I got another error:

> Error: Unrecognized command found at '^' position

which is caused by _get_remote_md5 ([here](https://github.com/napalm-automation-community/napalm-ce/blob/master/napalm_ce/ce.py#L1071))

in that function napalm tries to execute a command: 
`command = 'display system file-md5 {0}'.format(dst)`

That command does not exist on my device.
So I wonder what device this was tested on or if there is anything that has to be activated on the device before being able to use this driver.

**Comment by thddaniel** [comment]
@kebre001 Which version of device do you use? It seems that the problem is the version after V200R001C00 don't support this command.  
[CloudEngine 8800, 7800, 6800, and 5800 V200R001C00 Command Reference](https://support.huawei.com/enterprise/en/doc/EDOC1000120854?section=k005) 
[CloudEngine 8800, 7800, 6800, and 5800 V200R002C50](https://support.huawei.com/enterprise/en/doc/EDOC1000166501?idPath=24030814%7C21782165%7C21782239%7C22318536%7C21128158)

**Comment by kebre001** [comment]
hi @thddaniel 

Im using:
<HUAWEI>display version 
Huawei Versatile Routing Platform Software
VRP (R) software, Version 8.150 (CE6870EI V200R002C50SPC800)
Copyright (C) 2012-2017 Huawei Technologies Co., Ltd.
HUAWEI CE6870-24S6CQ-EI uptime is 5 days, 22 hours, 17 minutes 
Patch Version: V200R002SPH018

CE6870-24S6CQ-EI(Master) 1 : uptime is  5 days, 22 hours, 16 minutes
        StartupTime 2019/11/28   13:05:22 
Memory    Size    : 4096 M bytes
Flash     Size    : 1024 M bytes
CE6870-24S6CQ-EI version information                               
1. PCB    Version : CEM24S6CQP01   VER B
2. MAB    Version : 1
3. Board  Type    : CE6870-24S6CQ-EI
4. CPLD1  Version : 102
5. CPLD2  Version : 102
6. BIOS   Version : 386

So I guess that is a later version and is not supported with the current code?

**Comment by thddaniel** [comment]
@kebre001 yes. you can always replace the file instead of checking md5 value.

**Comment by kebre001** [comment]
I will clone the repo and try to get this fixed.
If you have any tips/suggestions how to proceed I would appreciate that.

Also a bit confused about the first error about python3 not being able to reverse a map.
Do you know if that works in python 2?

Thanks for the fast reply

**Comment by thddaniel** [comment]
I think it works fine with python2.7. Some APIs might doesn't make right with python3 because some of them are not covered by test.  You can fix it. 

Let's start by taking a look at the [NetworkDriver](https://napalm.readthedocs.io/en/latest/base.html).
If there are some problem of those API, you can check the [mock data](https://github.com/napalm-automation-community/napalm-ce/tree/master/test/unit) if they are the same format compared with the real device.  Because napalm use regular expressions to validate string values, some of mock data maybe outdated.

Thanks for following up @kebre001

**Comment by kebre001** [comment]
Hi @thddaniel 
Im having some issues testing the [load_merge_candidate](https://github.com/napalm-automation-community/napalm-ce/blob/master/napalm_ce/ce.py#L249) method in Saltstack.

Because there is no default input to (filename, config) I only get the MergeConfigException.

I dont really understand what the methods does either.
I understand that either you load a file with configuration or config provided in the CLI.
But the only thing the method does to to add the data to variables.
What happens next? The method does not return anything either.

Thanks for you help

**Comment by thddaniel** [comment]
After using load_merge_candidate method,  you can compare config.
>>> device.load_merge_candidate(config='hostname test\ninterface Ethernet2\ndescription bla')
>>> print(device.compare_config())

If you are happy with the changes you can commit them:
>>> device.commit_config()

On the contrary, if you don’t want the changes you can discard them:
>>> device.discard_config()

**Comment by kebre001** [comment]
Made a fork where I will make adjustments to work with Saltstack
